"""added User demo  fields

Revision ID: 0625390be133
Revises: cbca8370cfeb
Create Date: 2026-07-18 18:29:19.559110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0625390be133'
down_revision = 'cbca8370cfeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), nullable=False,server_default=sa.false()))
        batch_op.add_column(sa.Column('is_demo_data', sa.Boolean(), nullable=False,server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_demo_data')
        batch_op.drop_column('is_demo')

    # ### end Alembic commands ###
